# Generated by Django 2.2 on 2019-04-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.CharField(default='TechiesTalks', max_length=1000),
        ),
    ]
