# Generated by Django 2.2 on 2019-04-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Description',
            field=models.TextField(default='techiestalks'),
            preserve_default=False,
        ),
    ]
