# Generated by Django 2.2 on 2019-06-13 18:16

from django.db import migrations, models
import meta.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumb', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('keyword', models.CharField(default='TechiesTalks', max_length=1000)),
                ('Description', models.TextField()),
            ],
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
